name: uih-example-text-editor
version: 0.1.0.0
github: aantich/uih
license: BSD-3-Clause
author: UIH contributors
maintainer: UIH contributors
copyright: 2026 UIH contributors

dependencies:
  - base >= 4.20.2 && < 4.21
  - containers
  - filepath
  - text
  - uih-core

library:
  source-dirs: src
  exposed-modules:
    - Example.TextEditor

executables:
  uih-text-editor:
    main: Main.hs
    source-dirs: app
    dependencies:
      - uih-backend-appkit
      - uih-example-text-editor
      - uih-runtime
    ghc-options:
      - -Wall
      - -Wcompat
      - -threaded
    when:
      - condition: '!os(darwin)'
        buildable: false

tests:
  text-editor-model-test:
    main: ModelSpec.hs
    source-dirs: test/model
    dependencies:
      - uih-example-text-editor
  text-editor-native-test:
    main: NativeSpec.hs
    source-dirs: test/native
    dependencies:
      - directory
      - uih-backend-appkit
      - uih-example-text-editor
      - uih-runtime
    when:
      - condition: '!os(darwin)'
        buildable: false
