name: haskelui-example-appkit-vertical
version: 0.1.0.0
github: aantich/haskelui
license: BSD-3-Clause
author: HaskeLUI contributors
maintainer: HaskeLUI contributors
copyright: 2026 HaskeLUI contributors

dependencies:
  - base >= 4.20.2 && < 4.21
  - text
  - haskelui-backend-appkit
  - haskelui-core
  - haskelui-runtime

library:
  source-dirs: src
  exposed-modules:
    - Example.AppKitVertical

executables:
  haskelui-appkit-vertical:
    main: Main.hs
    source-dirs: app
    dependencies:
      - haskelui-example-appkit-vertical
    ghc-options:
      - -Wall
      - -Wcompat
      - -threaded
    when:
      - condition: '!os(darwin)'
        buildable: false

tests:
  appkit-vertical-native-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskelui-example-appkit-vertical
    when:
      - condition: '!os(darwin)'
        buildable: false
