name: uih-core
version: 0.1.0.0
github: aantich/uih
license: BSD-3-Clause
author: UIH contributors
maintainer: UIH contributors
copyright: 2026 UIH contributors

dependencies:
  - base >= 4.20.2 && < 4.21
  - text

ghc-options:
  - -Wall
  - -Wcompat

library:
  source-dirs: src

tests:
  uih-core-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - uih-core
