name: haskelui-example-control-gallery
version: 0.1.0.0
github: aantich/haskelui
license: BSD-3-Clause
author: HaskeLUI contributors
maintainer: HaskeLUI contributors
copyright: 2026 HaskeLUI contributors

dependencies:
  - base >= 4.20.1 && < 4.21
  - text
  - haskelui-core

library:
  source-dirs: src
  exposed-modules:
    - Example.ControlGallery
  ghc-options:
    - -Wall
    - -Wcompat

executables:
  haskelui-control-gallery:
    main: Main.hs
    source-dirs: app
    dependencies:
      - haskelui-backend-appkit
      - haskelui-example-control-gallery
      - haskelui-runtime
    ghc-options:
      - -Wall
      - -Wcompat
      - -threaded
    when:
      - condition: '!os(darwin)'
        buildable: false

tests:
  control-gallery-model-test:
    main: ModelSpec.hs
    source-dirs: test/model
    dependencies:
      - haskelui-backend-headless
      - haskelui-example-control-gallery
      - haskelui-runtime
  control-gallery-native-test:
    main: NativeSpec.hs
    source-dirs: test/native
    dependencies:
      - haskelui-backend-appkit
      - haskelui-example-control-gallery
      - haskelui-runtime
    when:
      - condition: '!os(darwin)'
        buildable: false
